server:
  servlet:
    context-path: /credit-tx-simulator

spring:
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: creditcard-tx-simulator-consumer
  kafka:
    topic: credit-card-transactions
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      properties:
        spring.json.add.type.headers: false
    streams:
      bootstrap-servers: localhost:9092
      application-id: credit-card-tx-app
      replicationFactor: 1
      commit-interval-ms: 2
      stateDir: ./tmp/kstreams
      cleanup:
        on-startup: true
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        # The number of threads to use for stream processing.
        num.stream.threads: 1
        commit.interval.ms: 1
        spring.json.trusted.packages: '*'
        spring.json.add.type.headers: false
        # Whether to clean up the local state store on application start.
    logging:
      level:
        org.apache.kafka.streams: DEBUG


springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

#Spring boot actuatore endpoints configuration

management:
  endpoints:
    web:
      exposure:
        include: 'health, kafkastreams'
